name: django-ecs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Set Up  Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
# docker hub를 이용할 때 사용
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: mh3769
      #     password: dckr_pat_psSd55_iVYzb59HnJa8YmORKvBs
  
      # - name: build and release to DockerHub
      #   env:
      #     NAME: mh3769
      #     REPO: django-ecs
      #   run: |
      #     docker build -t $REPO .
      #     docker tag $REPO:latest $NAME/$REPO:latest
      #     docker push $NAME/$REPO:latest
 
      - name: Build Docker Compose
        run: docker-compose

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::207955846572:role/Django-ECS-Role
          role-session-name: sampleSessionName
          aws-region: ap-northeast-2